import React, {useEffect, useRef, useState} from 'react';
import {api, sessionPath, captureMatches} from './api';
import {VoiceFontRecorder} from './recorder';
import {validate} from './wav';

export default function Calibration({notify, onLock, onFinalize}) {
  const [corpus,setCorpus]=useState(null), [session,setSession]=useState(null), [sessions,setSessions]=useState([]);
  const [promptId,setPromptId]=useState(''), [busy,setBusy]=useState(false), [draft,setDraft]=useState(null);
  const [recording,setRecording]=useState(false), [pending,setPending]=useState(false), [seconds,setSeconds]=useState(0), [level,setLevel]=useState(0);
  const [source,setSource]=useState(''), [status,setStatus]=useState('Ready when you are'), [finalize,setFinalize]=useState(false);
  const [name,setName]=useState('My voice'), [mode,setMode]=useState('full'), [consent,setConsent]=useState(false);
  const [voiceId,setVoiceId]=useState(''), [voiceName,setVoiceName]=useState('');
  const recorder=useRef(new VoiceFontRecorder()), audio=useRef(null), gate=useRef(false), binding=useRef(null), current=useRef({}), url=useRef(''), latest=useRef(null);
  const prompt=corpus?.prompts.find(p=>p.id===promptId), locked=busy||recording||pending, editable=session?.status==='active';
  current.current={sessionId:session?.id,promptId};
  function clearAudio(){audio.current?.pause(); if(url.current)URL.revokeObjectURL(url.current);url.current='';setSource('');}
  function playSource(value){clearAudio();if(value instanceof Blob){url.current=URL.createObjectURL(value);setSource(url.current);}else setSource(value);}
  function canLeave(){if(gate.current||recorder.current.active||recorder.current.pending||draft){notify('Save the unsaved take, or choose Re-record to discard it first.');return false;}return true;}
  async function operation(fn){if(gate.current)return;gate.current=true;setBusy(true);try{await fn();}catch(e){notify(e.message,true);}finally{gate.current=false;setBusy(false);}}
  const refresh=()=>api('/calibration/sessions').then(setSessions);
  useEffect(()=>{api('/calibration/corpus').then(c=>{latest.current=c;setCorpus(c);}).then(refresh).catch(e=>notify(e.message));return()=>{recorder.current.stop();if(url.current)URL.revokeObjectURL(url.current);};},[]);
  useEffect(()=>{onLock(locked||!!draft);const handler=e=>{if(locked||draft){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[locked,draft]);
  useEffect(()=>{const r=recorder.current;r.onlevel=setLevel;r.onduration=setSeconds;r.onfinish=(capture,reason)=>{captured(capture);if(reason)notify('Recording stopped. Replay the preserved take before saving.');};},[]);
  function captured(capture){setRecording(false);setPending(false);setLevel(0);if(!capture||capture.frames<capture.sampleRate*.1){setStatus('Take too short. Record at least 0.1 seconds, or import a WAV.');return;}
    if(!captureMatches(binding.current,current.current.sessionId,current.current.promptId)){notify('Recording context changed. Take not attached to another prompt.');return;}
    const blob=new Blob([recorder.current.encodeWav(capture)],{type:'audio/wav'});setDraft({...binding.current,blob,id:'take-'+crypto.randomUUID()});playSource(blob);setSeconds(capture.frames/capture.sampleRate);setStatus('Unsaved take. Replay, then save or re-record.');}
  async function record(){if(locked||draft||!editable)return;binding.current={...current.current};clearAudio();setPending(true);setStatus('Waiting for microphone permission.');try{if(await recorder.current.start()){setRecording(true);setStatus('Recording. Read naturally, then press Stop.');}}catch(e){notify('Microphone unavailable. Allow localhost microphone access or import PCM WAV. '+e.message);setStatus('Microphone unavailable');}finally{setPending(false);}}
  function choose(id){if(!canLeave())return;setPromptId(id);clearAudio();setStatus('Ready when you are');setSeconds(0);}
  async function show(s){const saved=await api(sessionPath(s.id)+'/corpus');setCorpus(saved);setSession(s);setPromptId(s.next_prompt_id||saved.prompts[0].id);setFinalize(false);clearAudio();}
  function next(s){const i=corpus.prompts.findIndex(p=>p.id===promptId);setPromptId(s.next_prompt_id&&s.next_prompt_id!==promptId?s.next_prompt_id:corpus.prompts[(i+1)%corpus.prompts.length].id);clearAudio();setStatus('Ready when you are');}
  async function save(){if(!draft||locked)return;if(!captureMatches(draft,session.id,promptId)){notify('Take belongs to a different session or prompt.');return;}await operation(async()=>{const s=await api(sessionPath(draft.sessionId)+'/takes?prompt_id='+encodeURIComponent(draft.promptId)+'&take_id='+draft.id,draft.blob,true);setSession(s);setDraft(null);next(s);notify('Take saved locally. Earlier takes are kept.');});}
  function discard(){if(locked)return;if(draft&&!confirm('Discard this unsaved take? All saved takes will be kept.'))return;setDraft(null);clearAudio();setStatus('Ready for a new take. All earlier saved takes are kept.');}
  async function importFile(e){const f=e.target.files[0];e.target.value='';if(!f||locked||draft)return;await operation(async()=>{if(f.size>50*1024*1024)throw new Error('WAV file exceeds 50 MB.');const context={...current.current};const b=await f.arrayBuffer();const info=validate(b);const blob=new Blob([b],{type:'audio/wav'});setDraft({...context,blob,id:'take-'+crypto.randomUUID()});playSource(blob);setSeconds(info.seconds);setStatus('Unsaved take. Replay, then save or re-record.');});}
  const accepted=session?.coverage.completed||0;
  return <section id="view-calibrate" className="workspace"><aside className="sidebar"><div className="eyebrow">RECORDING WORKSPACE · REACT</div><h1>Make room for<br/>your voice.</h1><p className="muted">One natural reading, one saved take at a time.</p><div className="progress-heading"><strong id="coverage-count">{accepted} / {corpus?.prompts.length||0} accepted</strong><span id="coverage-label">{session?.coverage.label||'Not started'}</span></div><progress id="coverage" max={corpus?.prompts.length||75} value={accepted}/><p className="small muted">Coverage counts recordings, not measured vocal ability.</p><div id="checklist" className="checklist">{corpus?.categories.map(c=><details key={c.id} open={prompt?.category===c.id}><summary>{c.title}</summary>{corpus.prompts.filter(p=>p.category===c.id).map(p=><button key={p.id} className={'prompt-choice '+(p.id===promptId?'current ':'')+(session?.accepted[p.id]?'accepted':'')} disabled={locked||!!draft||!session} aria-current={p.id===promptId?'step':undefined} title={p.text} onClick={()=>choose(p.id)}>{p.id} · {p.text.slice(0,42)}…</button>)}</details>)}</div></aside>
  <div className="workbench"><section id="setup" className="panel" hidden={!!session}><div className="eyebrow">01 / SET UP</div><h2>Start with a comfortable space.</h2><p>Use a quiet room and your natural accent. Stop if anything feels uncomfortable.</p><form id="start-form" onSubmit={e=>{e.preventDefault();if(!consent)return;operation(async()=>{const s=await api('/calibration/sessions',{name:name.trim(),consent:true,mode});await show(s);notify('Session started. Read only the prompt, not the delivery instruction.');});}}><label htmlFor="session-name">Session name</label><input id="session-name" value={name} onChange={e=>setName(e.target.value)} maxLength={128} required/><label htmlFor="session-mode">Recording order</label><select id="session-mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="full">Full checklist · in order</option><option value="adaptive">Balanced categories</option></select><label className="check-label"><input id="consent" type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>I own this voice or have explicit permission to record and use it for local profiles and speech synthesis.</span></label><button id="start-session" className="primary" disabled={busy||!corpus}>Start recording session</button></form><div className="resume-area"><h3>Continue a saved session</h3><div id="sessions-list">{sessions.map(s=><div className="session-row" key={s.id}><div><strong>{s.name}</strong><p>{s.coverage.completed} accepted · {s.status}</p></div><button disabled={busy} onClick={()=>{if(canLeave())operation(async()=>show(await api(sessionPath(s.id))));}}>{s.status==='finalized'?'View session':'Resume'}</button></div>)}</div><button id="refresh-sessions" onClick={()=>operation(refresh)}>Refresh sessions</button></div></section>
  <section id="studio" hidden={!session}><div className="studio-heading"><h2 id="session-title">{session?.name}</h2><button id="leave-session" disabled={locked} onClick={()=>{if(canLeave()){setSession(null);setCorpus(latest.current);setPromptId('');clearAudio();operation(refresh);}}}>Change session</button></div><article className="prompt-card"><div className="prompt-meta"><span id="prompt-category">{corpus?.categories.find(c=>c.id===prompt?.category)?.title}</span><span id="prompt-index">{promptId}</span></div><h3 className="eyebrow">READ ALOUD</h3><p id="prompt-text" className="prompt-text">{prompt?.text}</p><p id="prompt-instruction">{prompt?.instruction}</p><p className="small muted">Intended dimensions: {prompt?.dimensions.join(', ')}</p><div className="recording-strip"><span id="recorder-status" role="status">{status}</span><output id="recording-time">{Math.floor(seconds/60)}:{String(Math.floor(seconds%60)).padStart(2,'0')}</output><meter id="level" min="0" max="1" value={Math.min(1,level*4)}/></div><div className="button-row"><button id="record" className="primary" disabled={!editable||locked||!!draft} onClick={record}>Record</button><button id="stop" disabled={!recording&&!pending} onClick={()=>captured(recorder.current.stop())}>Stop</button><button id="replay" disabled={!source||locked} onClick={()=>{audio.current.currentTime=0;audio.current.play().catch(e=>notify(e.message));}}>Replay</button><button id="save" disabled={!draft||locked} onClick={save}>Save take &amp; next</button></div><audio id="take-audio" ref={audio} controls src={source||undefined} hidden={!source} onLoadedMetadata={()=>{if(source && !source.startsWith('blob:'))audio.current.play().catch(e=>notify(e.message));}}/><div className="button-row secondary"><button id="rerecord" disabled={locked||!editable} onClick={discard}>Re-record</button><button id="skip" disabled={locked||!!draft||!editable} onClick={()=>operation(async()=>{const s=await api(sessionPath(session.id)+'/skip',{prompt_id:promptId});setSession(s);next(s);notify('Prompt skipped.');})}>Skip prompt</button><button id="next" disabled={locked||!!draft||!session} onClick={()=>next(session)}>Next prompt</button></div><details className="import-area"><summary>Use an existing WAV recording instead</summary><label htmlFor="import-wav">Import authorised PCM WAV take</label><input id="import-wav" type="file" accept=".wav,audio/wav" disabled={locked||!!draft||!editable} onChange={importFile}/></details></article>
  <section className="takes-area"><h3>Saved takes for this prompt</h3><div id="takes-list">{session?.takes.filter(t=>t.prompt_id===promptId).map((t,i)=><div className="take-row" key={t.id}><div><strong>Take {i+1}{session.accepted[promptId]===t.id?' · selected':''}</strong><p>{t.duration_seconds.toFixed(1)} seconds · {t.style}</p></div><button disabled={locked||!!draft} onClick={()=>{playSource(sessionPath(session.id)+'/takes/'+t.id+'/audio');}}>Replay saved</button><button disabled={locked||!!draft||!editable||session.accepted[promptId]===t.id} onClick={()=>operation(async()=>{setSession(await api(sessionPath(session.id)+'/select',{prompt_id:promptId,take_id:t.id}));notify('Selected take updated. All saved takes are kept.');})}>{session.accepted[promptId]===t.id?'Selected':'Use this take'}</button></div>)}</div></section>
  <section className="session-actions panel"><h3>Pause here or make a profile</h3><p>A partial profile needs 3 accepted prompts across 2 categories. Saved takes persist automatically.</p><div className="button-row"><a id="export-session" className="button" href={session?sessionPath(session.id)+'/export':undefined} download>Export backup</a><button id="show-finalize" disabled={locked||!!draft||!editable} onClick={()=>{setFinalize(true);setVoiceName(session.pending_finalization?.name||session.name);setVoiceId(session.pending_finalization?.voice_id||'');}}>Create voice profile</button></div><form id="finalize-form" hidden={!finalize} onSubmit={e=>{e.preventDefault();operation(async()=>{const p=await api(sessionPath(session.id)+'/finalize',{voice_id:voiceId,name:voiceName});setSession(await api(sessionPath(session.id)));setFinalize(false);notify('Profile created: '+p.name);onFinalize();});}}><p id="finalize-summary">{accepted} accepted prompts across {Object.values(session?.coverage.by_category||{}).filter(c=>c.completed>0).length} categories. The best neutral reference is selected; the whole session is preserved.</p><label htmlFor="voice-id">Profile ID</label><input id="voice-id" value={voiceId} onChange={e=>setVoiceId(e.target.value)} pattern={'[a-z0-9][a-z0-9_\\-]{0,63}'} required/><label htmlFor="voice-name">Display name</label><input id="voice-name" value={voiceName} onChange={e=>setVoiceName(e.target.value)} maxLength={128} required/><button type="submit" disabled={busy}>Finalize profile</button><button id="cancel-finalize" type="button" onClick={()=>setFinalize(false)}>Not yet</button></form></section></section></div></section>;
}
