import React,{useEffect,useRef,useState} from 'react';
import {api,jobPath} from './api';
export default function Speech({active,profiles,voice,setVoice,notify}){
 const [cap,setCap]=useState(null),[text,setText]=useState(''),[speed,setSpeed]=useState(1),[job,setJob]=useState(null),[manual,setManual]=useState(false),[submitting,setSubmitting]=useState(false);
 const timer=useRef(null),current=useRef(null),budget=useRef(240);current.current=job;
 useEffect(()=>{if(active)api('/synthesis/capabilities').then(setCap).catch(e=>notify(e.message));},[active]);
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 async function check(id=current.current?.id){clearTimeout(timer.current);if(!id)return;try{const j=await api(jobPath(id));if(current.current?.id!==id)return;setJob(j);setManual(false);if(['running','queued'].includes(j.status)){if(budget.current-->0)timer.current=setTimeout(()=>check(id),1500);else setManual(true);}}catch(e){setManual(true);notify('Status check failed: '+e.message);}}
 async function submit(e){e.preventDefault();if(submitting||running)return;setSubmitting(true);setJob(null);setManual(false);try{const j=await api('/synthesis/jobs',{voice_id:voice,text:text.trim(),style:'neutral',speed});current.current=j;setJob(j);budget.current=240;await check(j.id);}catch(e){setJob({status:'failed',error:e.message});notify(e.message);}finally{setSubmitting(false);}}
 async function cancel(){const id=job?.id;if(!id)return;clearTimeout(timer.current);try{const j=await api(jobPath(id)+'/cancel',{});setJob(j);current.current=j;if(['running','queued'].includes(j.status)){setManual(true);timer.current=setTimeout(()=>check(id),1500);}}catch(e){notify('Cancellation request failed: '+e.message);setManual(true);timer.current=setTimeout(()=>check(id),1500);}}
 const running=job&&['running','queued'].includes(job.status);
 return <section id="view-speech" className="single-view"><div className="eyebrow">TEXT TO AUDIO</div><h1>Create speech</h1><p>Reference-based local conversion. Listen to assess quality; capturing a style does not guarantee synthesis of it.</p><div id="capability" className="panel" role="status">{cap?(cap.available?'Engine configured: ':'Engine unavailable. ')+cap.message:'Checking local speech engine…'}</div><form id="synthesis-form" className="panel" onSubmit={submit}><label htmlFor="speech-voice">Voice profile</label><select id="speech-voice" value={voice} onChange={e=>setVoice(e.target.value)} required><option value="">Choose a profile</option>{profiles.map(p=><option key={p.voice_id} value={p.voice_id}>{p.name}</option>)}</select><label htmlFor="speech-text">What should it say?</label><textarea id="speech-text" rows={6} maxLength={1000} required value={text} onChange={e=>setText(e.target.value)}/><div className="field-footer"><span>{text.length} / 1,000 characters</span><span>Neutral style</span></div><label htmlFor="speech-speed">Speed {speed.toFixed(2)}×</label><input id="speech-speed" type="range" min="0.75" max="1.5" step="0.05" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/><div className="button-row"><button id="generate" className="primary" disabled={!cap?.available||!!running||submitting}>Generate speech</button><button id="cancel-job" type="button" disabled={!running} onClick={cancel}>Cancel job</button></div></form><div id="job-panel" className="panel" hidden={!job&&!submitting}><h2>Speech output</h2><p id="job-status" role="status">{submitting?'Submitting local speech job…':job?'Status: '+job.status+(job.error?'. '+job.error:''):''}</p><button id="check-job" hidden={!manual} onClick={()=>{budget.current=240;check();}}>Check job status</button><audio id="speech-audio" controls hidden={job?.status!=='completed'} src={job?.status==='completed'?jobPath(job.id)+'/audio':undefined}/><a id="download-speech" className="button" hidden={job?.status!=='completed'} href={job?.status==='completed'?jobPath(job.id)+'/audio':undefined} download="voicefont-speech.wav">Download WAV</a></div></section>;
}
