artifact_uri: file:C:\Projects\VoiceFont\training\tts_output\mlflow/148444324272156404/8196fae976aa4e9bae8ac3ea55c2cc17/artifacts
end_time: 1789684114587
entry_point_name: ''
experiment_id: '148444324272156404'
lifecycle_stage: active
run_id: 8196fae976aa4e9bae8ac3ea55c2cc17
run_name: tts_text2mel_smoke
run_uuid: 8196fae976aa4e9bae8ac3ea55c2cc17
source_name: ''
source_type: 4
source_version: ''
start_time: 1789684111502
status: 3
tags: []
user_id: Chris
